[workspace]
members = [
  "dlrkit",
  "mmor",
  "mrevise" ,
  "afnative",
  "examples/libcproxy",
  "examples/aom-dll-hijack/aomlib",
  "examples/aom-dll-hijack/client",
  "examples/aom-dll-hijack/server",
]
resolver = "3"

[workspace.package]
version = "0.1.2"
authors = ["Stephen Fox Jr. <stephen.j.fox.jr@gmail.com>"]
license = "MIT"
description = """
libgib is a collection of Rust libraries that support building programs
that run inside other programs via code injection. libgib's libraries
provide OS-agnostic tooling to help locate code and data in the current
process and manipulate the underlying memory."""
repository = "https://codeberg.org/stephen-fox/libgib"
